export enum WINDOWS_ACTION {
  CREATE_WINDOW = 'CREATE_WINDOW',
  DELETE_WINDOW = 'DELETE_WINDOW',
  UPDATE_WINDOW = 'UPDATE_WINDOW',
  UPDATE_METADATA = 'UPDATE_METADATA',
  TOP_WINDOW = 'TOP_WINDOW',
}
